name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repo so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake
      - uses: Platane/snk@v3.2.0
        id: snake-gif
        with:
          github_user_name: jeetrico
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build. Useful for debugging.
      - run: git status

      # Commit and push the generated files to the output branch
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/
          git commit -m "Update snake contribution graph"
          git push origin master

      # Deploy the files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages  # Use the branch where GitHub Pages is configured
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
